portal/urls.py
from django.urls import path, include

from .views import index

app_name = 'portal'

urlpatterns = [
    path('signup/', index.PortalIndex.as_view(), name='portal-index'),

    #portal urls
    path('dashboard/', index.dashboard, name='portal-dashboard'),
    path('dashboard/add_update_student/', index.add_update, name='portal-dashboard-add'),
    path('dashboard/student_payment/', index.student_payment, name='portal-student-payment'),
    path('dashboard/Send_mail/', index.send_mail_to, name='portal-dashboard-mail'),
    #End portal Url
]

school/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from portal.views import index, student, teacher
from django.contrib.auth import views

from rest_framework import routers
from portal.api.views import StudentViewSet, StudentPaymentViewSet

# Create a router and register our viewsets with it.
router = routers.DefaultRouter()
router.register(r'student', StudentViewSet)
router.register(r'student_payment', StudentPaymentViewSet)


# The API URLs are now determined automatically by the router.
# Additionally, we include the login URLs for the browsable API.


urlpatterns = [
    re_path('portal/dashboard/add_update_student/api/', include(router.urls)),
    re_path('portal/dashboard/student_payment/api/', include(router.urls)),

    path('admin/', admin.site.urls),
    path('portal/', include('portal.urls')),
    path('', index.student_count),
    path('about-us/', index.AboutView.as_view(), name="about-us"),
    path('contact-us/', index.ContactView.as_view(), name="contact-us"),

    # Autenticate 3rd party
    path('portal/login/', views.LoginView.as_view(), name='login'),
    path('portal/logout/', views.LogoutView.as_view(), name='logout'),
    path('portal/password_reset/', views.PasswordResetView.as_view(), name='password_reset'),
    path('portal/password_reset/done/', views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('portal/reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('portal/reset/done/', views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

    path('portal/signup/student/', student.StudentSignUpView.as_view(), name='student_signup'),
    path('portal/signup/teacher/', teacher.TeacherSignUpView.as_view(), name='teacher_signup'),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL,
        document_root=settings.STATIC_ROOT
    )
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

portal/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.db import transaction
from django.forms.utils import ValidationError
from django.contrib.auth.forms import PasswordResetForm
from .models import Teacher, Student, User


class EmailValidationOnForgotPassword(PasswordResetForm):
    def clean_email(self):
        email = self.cleaned_data['email']
        if not User.objects.filter(email__iexact=email,
                                   is_active=True).exists():
            raise ValidationError("There is no user registered \
                                  with the specified email address!")

        return email


class TeacherSignUpForm(UserCreationForm):
    '''
        Signup form for teachers
    '''
    email = forms.EmailField(max_length=254,
                             required=True,
                             help_text='Required. Input a valid email addresse')

    class Meta(UserCreationForm.Meta):
        model = User
        fields = ["username", "first_name", "last_name"]

    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email__iexact=email, is_active=True).exists():
            raise ValidationError("Email already exists!")
        return email

    def save(self, commit=True):
        user = super().save(commit=False)
        user.user_type = 2
        if commit:
            user.save()
        return user


class StudentSignUpForm(UserCreationForm):
    '''
        Signup form for students
    '''
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('username', 'first_name',
                  'last_name', 'profile_image',
                  'email', 'residential_address',
                  'phone_number',)

    def save(self, commit=True):
        user = super().save(commit=False)
        user.user_type = 1
        if commit:
            user.save()
        return user

    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email__iexact=email, is_active=True).exists():
            raise ValidationError("Email already exists!")
        return email


class PostEmail(forms.Form):
    name = forms.CharField(max_length=35,
                           widget=forms.TextInput(attrs={'class': 'form-control-lg input-name', 'readonly':''})
                           )
    subject = forms.CharField(max_length=25,
                              widget=forms.TextInput(attrs={'class': 'form-control-lg', 'placeholder': 'difficulties... '})
                              )
    sender = forms.EmailField(widget=forms.TextInput(attrs={'class': 'form-control-lg input-mailsender', 'readonly':''}))
    #receipient = forms.EmailField()
    message = forms.CharField(required=True, widget=forms.Textarea)

portal/api/views.py
from django.shortcuts import render
from rest_framework import viewsets
from portal.models import Student, StudentTutionPayment
from rest_framework.permissions import IsAuthenticatedOrReadOnly
from portal.api.serializers import StudentSerializer, StudentTutionPaymentSerializer


class StudentViewSet(viewsets.ModelViewSet):
    """
    A simple ViewSet for viewing and editing the s.
    """
    queryset = Student.objects.all()
    serializer_class = StudentSerializer

class StudentPaymentViewSet(viewsets.ModelViewSet):
    """
    A simple ViewSet for viewing and editing the states.
    """
    queryset = StudentTutionPayment.objects.all()
    serializer_class = StudentTutionPaymentSerializer

portal/views/index.py
from django.shortcuts import render
from django.views.generic.base import TemplateView
from django.shortcuts import render
from django.contrib.auth.views import PasswordResetView
from portal.models import Student, Teacher, User
from django.contrib.auth.decorators import login_required
from django.core.mail import BadHeaderError, send_mail, get_connection
from django.contrib import messages
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

from portal.forms import PostEmail
from portal.decorators import student_required, teacher_required
from portal.forms import EmailValidationOnForgotPassword


PasswordResetView.form_class = EmailValidationOnForgotPassword


class PortalIndex(TemplateView):
    template_name = 'portal/index.html'


class AboutView(TemplateView):
    template_name = 'aboutus.html'

    def get_context_data(self, **kwargs):
        context = super(AboutView, self).get_context_data(**kwargs)
        context['teachers'] = Teacher.objects.all()
        return context


class ContactView(TemplateView):
    template_name = 'contact.html'


# Get the student and teachers count
def student_count(request):
    # instance_list = User.objects.all()
    student_instance = User.objects.filter(user_type__contains=1).count()
    teacher_instance = User.objects.filter(user_type__contains=2).count()
    context = {
        'student_instance': student_instance,
        'teacher_instance': teacher_instance,
    }
    return render(request, 'index.html', context)

# Manin dashboard views
@login_required
def dashboard(request):
    # dashbord views
    return render(request, 'portal/dashboard.html')

@teacher_required
def add_update(request):
    # add student tables
    return render(request, 'portal/table-forms.html')

@teacher_required
def student_payment(request):
    # get the student payments Student payment views
    return render(request, 'portal/payment_table.html')


@login_required
def send_mail_to(request):
    # instance_list = User.objects.all()
    form = PostEmail(request.POST)
    if request.method == 'POST':
        if form.is_valid():
            name = form.cleaned_data['name']
            subject = form.cleaned_data['subject']
            sender = form.cleaned_data['sender']
            message = form.cleaned_data['message']
            name_and_subject = f'{name} on {subject}'
            reciepients = ['admin@example.com']
            try:
                send_mail(name_and_subject,
                          message, sender,
                          reciepients,)
            except BadHeaderError:
                return HttpResponse('Invalid header found.')
            messages.success(request, f"Thanks <strong>{ request.user.first_name }</strong>, your message has been successfully sent", extra_tags='html_safe')
            return HttpResponseRedirect('')
    else:
        form = PostEmail()

    context = {
        'form': form,
    }

    return render(request, 'portal/mail-forms.html', context)

portal/views/student.py
from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.db.models import Count
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, ListView, UpdateView

from ..decorators import teacher_required
from ..forms import StudentSignUpForm
from portal.models import Student, User


@method_decorator([login_required, teacher_required], name='dispatch')
class StudentSignUpView(CreateView):
    model = User
    form_class = StudentSignUpForm
    template_name = 'registration/signup_form.html'

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'student'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('portal:portal-index')

portal/views/teacher.py
from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.db.models import Avg, Count
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import (CreateView,
                                  DeleteView,
                                  DetailView,
                                  ListView,
                                  UpdateView)
from django.contrib.admin.views.decorators import staff_member_required
from portal.decorators import teacher_required
from portal.forms import TeacherSignUpForm
from portal.models import User


@method_decorator([login_required, staff_member_required], name='dispatch')
class TeacherSignUpView(CreateView):
    model = User
    form_class = TeacherSignUpForm
    template_name = 'registration/signup_form.html'

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'teacher'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('portal:portal-index')

portal/templates/portal/include/dashboard-nav.html
<nav class="navbar navbar-expand navbar-dark bg-primary">
        <a class="sidebar-toggle mr-3" href="#"><i class="fa fa-bars"></i></a>
        <a class="navbar-brand" href="#">GGS Portal</a>

        <div class="navbar-collapse collapse container">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item"><a href="#" class="nav-link"><i class="fa fa-envelope"></i> </a></li>
                <li class="nav-item"><a href="#" class="nav-link"><i class="fa fa-bell"></i> 3</a></li>
                <li class="nav-item dropdown">
                    <a href="#" id="dd_user" class="nav-link dropdown-toggle" data-toggle="dropdown">
                        {% if request.user.is_authenticated %}<img class="profile-image1" src='{{ request.user.profile_image.url }}' alt="{{ request.user.username }} profile image">{% endif %}
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dd_user">
                        <a href="#" class="dropdown-item">
                                {% if request.user.is_authenticated %}
                                    Hello {{ request.user.username }},
                                    <a href="{% url "logout" %}" class="dropdown-item">Logout</a>
                                {% else %}
                                    <a href="{% url "login" %}">Log-in</a>
                                {% endif %}
                            </span>
                        </div>
                    </div>
                </li>
            </ul>
        </div>
    </nav>

portal/templates/portal/include/dashboard_sidenav.html
<div class="sidebar sidebar-dark bg-dark">
        <ul class="list-unstyled">
            {% if request.user.user_type == 1 %}
                <li><a href="{% url 'portal:portal-dashboard' %}"><i class="fa fa-user"></i> Student Proile</a></li>
                <li><a href="#"><i class="fa fa-id-card-o"></i> Chech result</a></li>
            {% elif request.user.user_type == 2 %}
                <li><a href="{% url 'portal:portal-dashboard' %}"><i class="fa fa-user"></i> Teacher Proile</a></li>
                <li><a href="{% url 'portal:portal-dashboard-add' %}"><i class="fa fa-id-card-o"></i> Update & Add Students</a></li>
                <li><a href="{% url 'portal:portal-student-payment' %}"><i class="fa fa-id-card-o"></i> Students payment</a></li>

            {% endif %}

            <li><a href="{% url 'portal:portal-dashboard-mail' %}"><i class="fa fa-envelope"></i> Send Message</a></li>
            <li><a href="#"><i class="fa fa-bell"></i> Inbox</a></li>


        </ul>
    </div>

portal/templates/portal/include/profile-card.html
{% load staticfiles %}

<div class="card mb-4">
        <div class="card-body">
            {% if request.user.is_authenticated %}
            <div class="info-body">
                <div class="info-header ">
                    <div style="background: url({% static 'img/logo.png' %});"></div>
                </div>
                <div class="info-personal">
                    {% if request.user.is_authenticated %}<img data-toggle="tooltip" data-placement="bottom" title="" data-original-title="{{ request.user.first_name }}'s image" class="img-thumbnail profile-image1" src='{{ request.user.profile_image.url }}' alt="{{ request.user.username }} profile image">{% endif %}
                    <h3>personal information</h3>
                    <table class="table">
                        <tbody>
                            <tr>
                                <td>First Name:</td>
                                <td>{{ request.user.first_name }}</td>
                            </tr>
                            <tr>
                                <td>Last Name:</td>
                                <td>{{ request.user.last_name }}</td>
                            </tr>
                            <tr>
                                <td>Username:</td>
                                <td><span style="color: red">{{ request.user.username }}</span></td>
                            </tr>
                            <tr>
                                <td>Email:</td>
                                <td>{{ request.user.email }}</td>
                            </tr>
                            <tr>
                                <td>DOB:</td>
                                <td>{{ request.user.date_of_birth }}</td>
                            </tr>
                            <tr>
                                <td>User Type:</td>
                                <td>{% if request.user.user_type == 1 %}  Student
                                        {% else %} Teacher
                                    {% endif %}
                                </td>
                            </tr>
                            {% if request.user.user_type == 1 %}
                                <tr>
                                    <td>Current class:</td>
                                    <td>{{ request.student.class_in }}</td>
                                </tr>
                                <tr>
                                    <td>Teacher Name:</td>
                                    <td>{{ request.user.email }}</td>
                                </tr>
                            {% endif %}
                        </tbody>
                    </table>

                    <h3>contact information</h3>
                    <table class="table">
                        <tbody>
                            <tr>
                                <td>Phone Number:</td>
                                <td>{{ request.user.phone_number }}</td>
                            </tr>
                            <tr>
                                <td>Home Address:</td>
                                <td>{{ request.user.residential_address }}</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                <div class="info-contact">

                </div>
            </div>
            {% else %}
                you are not permitted
            {% endif %}
        </div>
    </div>