portal/urls.py
from django.urls import path, include

from .views import index

app_name = 'portal'

urlpatterns = [
    path('signup/', index.PortalIndex.as_view(), name='portal-index'),

    #portal urls
    path('dashboard/', index.dashboard, name='portal-dashboard'),
    path('dashboard/add_update_student/', index.add_update, name='portal-dashboard-add'),
    path('dashboard/student_payment/', index.student_payment, name='portal-student-payment'),
    path('dashboard/Send_mail/', index.send_mail_to, name='portal-dashboard-mail'),
    #End portal Url
]

school/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from portal.views import index, student, teacher
from django.contrib.auth import views

from rest_framework import routers
from portal.api.views import StudentViewSet, StudentPaymentViewSet

# Create a router and register our viewsets with it.
router = routers.DefaultRouter()
router.register(r'student', StudentViewSet)
router.register(r'student_payment', StudentPaymentViewSet)


# The API URLs are now determined automatically by the router.
# Additionally, we include the login URLs for the browsable API.


urlpatterns = [
    re_path('portal/dashboard/add_update_student/api/', include(router.urls)),
    re_path('portal/dashboard/student_payment/api/', include(router.urls)),

    path('admin/', admin.site.urls),
    path('portal/', include('portal.urls')),
    path('', index.student_count),
    path('about-us/', index.AboutView.as_view(), name="about-us"),
    path('contact-us/', index.ContactView.as_view(), name="contact-us"),

    # Autenticate 3rd party
    path('portal/login/', views.LoginView.as_view(), name='login'),
    path('portal/logout/', views.LogoutView.as_view(), name='logout'),
    path('portal/password_reset/', views.PasswordResetView.as_view(), name='password_reset'),
    path('portal/password_reset/done/', views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('portal/reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('portal/reset/done/', views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

    path('portal/signup/student/', student.StudentSignUpView.as_view(), name='student_signup'),
    path('portal/signup/teacher/', teacher.TeacherSignUpView.as_view(), name='teacher_signup'),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL,
        document_root=settings.STATIC_ROOT
    )
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

templates/aboutus.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}{{ block.super }} || Home {% endblock %}

{% block content %}

	<!-- Breadcrumb section -->
	<div class="site-breadcrumb">
		<div class="container">
			<a href="/"><i class="fa fa-home"></i> Home</a> <i class="fa fa-angle-right"></i>
			<span>About Us</span>
		</div>
	</div>
	<!-- Breadcrumb section end -->


	<!-- About section -->
	<section class="about-section spad pt-0">
		<div class="container">
			<div class="section-title text-center">
				<h3>WELCOME TO GOLDEN GATE</h3>
				<p>Let children creative and make a different</p>
			</div>
			<div class="row">
				<div class="col-lg-6 about-text">
					<h5>About us</h5>
					<p>Lorem ipsum dolor sitdoni amet, consectetur dont adipis elite. Vivamus interdum ultrices augue. Aenean dos cursus lania. Duis et fringilla leonardo. Mauris mattis phare sem, debut curus risus viverra sed.</p>
					<h5 class="pt-4">Our history</h5>
					<p>Led at felis arcu. Integer lorem lorem, tincidunt eu congue et, mattis ut ante. Nami suscipit, lectus id efficitur ornare, leo libero convalis nulla, vitae dignissim .</p>
					<ul class="about-list">
						<li><i class="fa fa-check-square-o"></i> Golden Gate school organise teaching and research into individual subjects.</li>
						<li><i class="fa fa-check-square-o"></i> The school is rich in history - its famous buildings attract visitors.</li>
						<li><i class="fa fa-check-square-o"></i> 20 years of people, and achievements that continue to transform.</li>
						<li><i class="fa fa-check-square-o"></i> The school's core values are as follows:freedom of thought.</li>
					</ul>
				</div>
				<div class="col-lg-6 pt-5 pt-lg-0">
					<img src="{% static 'img/about.jpg' %}" alt="">
				</div>
			</div>
		</div>
	</section>
	<!-- About section end-->


	<!-- Testimonial section  -->
	<section class="testimonial-section spad">
		<div class="container">
			<div class="section-title text-center">
				<h3>OUR TEACHER'S</h3>
				<p>The professional standards and expectations</p>
			</div>
			<div class="testimonial-slider owl-carousel">
				{% for teacher in teachers %}
				<div class="ts-item">

					<div class="row">
							{% if teacher %}
								<div class="col-md-3">
									<div class="ts-author-pic set-bg" data-setbg="{{ teacher.user.profile_image.url }}" style="background-image: url(&quot;img/member/5.jpg&quot;);"></div>
								</div>
								<div class="col-md-9 ts-text">
									<p>“ I want to let you know that I am very absolutely delighted with the pupils, student and parents of Golden Gate school. ”</p>
									<h5>{{ teacher.title }}. {{ teacher.user.first_name }} {{ teacher.user.last_name }}</h5>
									<span>Teacher</span>
								</div>
							{% else %}
								processing.... Not found 🐽
							{% endif %}
					</div>

				</div>
				{% endfor %}
			</div>
		</div>
	</section>
	<!-- Testimonial section end -->
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
	<title>{% block title %}Golden Gate School {% endblock %}</title>
	<meta charset="UTF-8">
	<meta name="description" content="Golden gate school website">
	<meta name="keywords" content="school portal, school management system">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<!-- Favicon -->
	<link href="{% static 'img/favicon.ico' %}" rel="shortcut icon"/>

	<!-- Google Fonts -->
	<link href="https://fonts.googleapis.com/css?family=Rubik:400,400i,500,500i,700,700i" rel="stylesheet">

	<!-- Stylesheets -->
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<link rel="stylesheet" href="{% static 'css/font-awesome.min.css'%}"/>
	<link rel="stylesheet" href="{% static 'css/themify-icons.css'%}"/>
	<link rel="stylesheet" href="{% static 'css/magnific-popup.css'%}"/>
	<link rel="stylesheet" href="{% static 'css/animate.css' %}"/>
	<link rel="stylesheet" href="{% static 'css/owl.carousel.css' %}"/>
	<link rel="stylesheet" href="{% static 'css/style.css' %}"/>


	<!--[if lt IE 9]>
	  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js" %}"></script>
	  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js" %}"></script>
	<![endif]-->

</head>
<body data-spy="scroll" data-target=".navbar" data-offset="50">
	<!-- Page Preloder -->
	<div id="preloder">
		<div class="loader"></div>
	</div>

	<!-- header section -->
	<header class="header-section">
		<div class="container">
			<!-- logo -->
			<a href="/" class="site-logo"><img src="{% static 'img/logo.png' %}" alt=""></a>
			<div class="nav-switch">
				<i class="fa fa-bars"></i>
			</div>
			<div class="header-info">
				<div class="hf-item">
					<i class="fa fa-clock-o"></i>
					<p><span>School Time:</span>Monday - Friday: 08 AM - 06 PM</p>
				</div>
				<div class="hf-item">
					<i class="fa fa-map-marker"></i>
					<p><span>Find us:</span>Gbazango Extension, Kubwa, Abuja</p>
				</div>
			</div>
		</div>
	</header>
	<!-- header section end-->


	<!-- Header section  -->
	<nav class="nav-section">
		<div class="container">
			<div class="nav-right">
				<a href=""><i class="fa fa-search"></i></a>
				<a href="{% url 'portal:portal-index' %}"><i class="fa fa-group"></i> PORTAL</a>
			</div>
			<ul class="main-menu">
				<li class="active"><a href="/">Home</a></li>
				<li><a href="{% url 'about-us' %}">About Us</a></li>
				<li><a href="#">PGGS Profile</a></li>
				<li><a href="course.html">PGGS Message</a></li>
				<li><a href="blog.html">Gallery</a></li>
				<li><a href="{% url 'contact-us' %}">Contact</a></li>
			</ul>
		</div>
	</nav>
	<!-- Header section end -->

    {% block content %}

    {% endblock content %}


	<!-- Footer section -->
	<footer class="footer-section">
		<div class="container footer-top">
			<div class="row">
				<!-- widget -->
				<div class="col-sm-6 col-lg-3 footer-widget">
					<div class="about-widget">
						<img style="padding: 5px;" src="{% static 'img/logo.png' %}" alt="">
						<p>Golden  Gate School is an Abuja based school, That has an an Amazing and spectacular record </p>
						<div class="social pt-1">
							<a href=""><i class="fa fa-twitter-square"></i></a>
							<a href=""><i class="fa fa-facebook-square"></i></a>
							<a href=""><i class="fa fa-google-plus-square"></i></a>
							<a href=""><i class="fa fa-linkedin-square"></i></a>
							<a href=""><i class="fa fa-rss-square"></i></a>
						</div>
					</div>
				</div>
				<!-- widget -->
				<div class="col-sm-6 col-lg-3 footer-widget">
					<h6 class="fw-title">USEFUL LINK</h6>
					<div class="dobule-link">
						<ul>
							<li><a href="">Home</a></li>
							<li><a href="">About us</a></li>
							<li><a href="">PGGS Profile</a></li>
						</ul>
						<ul>
							<li><a href="">PGGS Message</a></li>
							<li><a href="">Gallery</a></li>
							<li><a href="">Contact</a></li>
						</ul>
					</div>
				</div>
				<!-- widget -->
				<div class="col-sm-6 col-lg-3 footer-widget">
					<h6 class="fw-title">OUR MISSION</h6>
					<ul class="recent-post">
						<li>
							<p>We want to impact <br> the next generation</p>
						</li>
						<li>
							<p>moulding the future <br> of our society</p>
						</li>
					</ul>
				</div>
				<!-- widget -->
				<div class="col-sm-6 col-lg-3 footer-widget">
					<h6 class="fw-title">CONTACT</h6>
					<ul class="contact">
						<li><p><i class="fa fa-map-marker"></i>Gbazango Extension, Kubwa, Abuja</p></li>
						<li><p><i class="fa fa-phone"></i> (+234) 810 555 666</p></li>
						<li><p><i class="fa fa-envelope"></i> mail@gmail.com</p></li>
						<li><p><i class="fa fa-clock-o"></i> Monday - Friday, 08:00AM - 04:00 PM</p></li>
					</ul>
				</div>
			</div>
		</div>
		<!-- copyright -->
		<div class="copyright">
			<div class="container">
				<p>
					Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | Built with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://silvareal.github.io" target="_blank">sylvernus</a>
				</p>
			</div>
		</div>
	</footer>
	<!-- Footer section end-->



	<!--====== Javascripts & Jquery ======-->
	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
	<script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
	<script src="{% static 'js/owl.carousel.min.js' %}"></script>
	<script src="{% static 'js/jquery.countdown.js' %}"></script>
	<script src="{% static 'js/masonry.pkgd.min.js' %}"></script>
	<script src="{% static 'js/magnific-popup.min.js' %}"></script>
	<script src="{% static 'js/main.js' %}"></script>

	{% block javascript %}

	{% endblock javascript %}

</body>
</html>

templates/contact.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}{{ block.super }} || Home {% endblock %}

{% block content %}


	<!-- Breadcrumb section -->
	<div class="site-breadcrumb">
		<div class="container">
			<a href="/"><i class="fa fa-home"></i> Home</a> <i class="fa fa-angle-right"></i>
			<span>Contact</span>
		</div>
	</div>
	<!-- Breadcrumb section end -->


	<!-- Courses section -->
	<section class="contact-page spad pt-0">
		<div class="container">

			<!-- contact form -->
			<div class="contact-form spad pb-0">
				<div class="section-title text-center">
					<h3>GET IN TOUCH</h3>
					<p>Contact us for more enquirely</p>
				</div>

				<form class="comment-form --contact" method="POST" action="">
					<div class="row">
						<div class="col-lg-4">
							<input type="text" placeholder="Your Name">
						</div>
						<div class="col-lg-4">
							<input type="text" placeholder="Your Email">
						</div>
						<div class="col-lg-4">
							<input type="text" placeholder="Subject">
						</div>
						<div class="col-lg-12">
							<textarea placeholder="Message"></textarea>
							<div class="text-center">
								<button class="site-btn">SUBMIT</button>
							</div>
						</div>
					</div>
				</form>
			</div>
			<!-- End contact form -->

			<!-- Contact card-->
			<div class="row" style="justify-content: center; margin-top: 50px;">
				<div class="col-md-5">
					<div class="map-section">
						<div class="contact-info-warp">
							<div class="contact-info">
								<h4>Address</h4>
								<p>40 Baria Street 133/2, NewYork City, US</p>
							</div>
							<div class="contact-info">
								<h4>Phone</h4>
								<p>(+88) 111 555 666</p>
							</div>
							<div class="contact-info">
								<h4>Email</h4>
								<p>infodeercreative@gmail.com</p>
							</div>
							<div class="contact-info">
								<h4>Working time</h4>
								<p>Monday - Friday: 08 AM - 06 PM</p>
							</div>
						</div>
					</div>
				</div>

			<!---
				<div class="col-md-6">
					<div id="map" class="map" style="width:100%;height:400px;"></div>

				</div>
			-->
			</div>
			<!-- End contact card-->

		</div>
	</section>
	<!-- Courses section end-->


{% endblock %}

templates/message_display.html
{% if messages %}

A simple primary alert—check it out!

<div class="alert alert-primary alert-dismissible" role="alert">
    <div class="messages">
        <ul class="messages">
            {% for message in messages %}
                <li class="{{ message.tags }}" style="list-style: none; font-size: 15px;">
                    {% if 'html_safe' in message.tags %}{{ message|safe }}{% else %}{{ message}}{% endif %}
                </li>
            {% endfor %}
        </ul>
    </div>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">×</span>
    </button>
</div>
{% endif %}

templates/user_count.html
{% load staticfiles %}

<div style="display: flex; justify-content: center">

        <div style="background:rgb(144, 198, 230); height: 60px; width: 100px; border-radius: 10px;color: white; border: 2px sold rgb(62, 62, 180); margin: 20px;padding:5px;">
            <p style="text-align: center;">
                <img style="max-width: 30px" src="{% static 'img/portal/student.png' %}" alt=""><br>{{titles}} {{instance}}

            </p>
        </div>

        <div style="background:rgb(144, 198, 230); height: 60px; width: 100px; border-radius: 10px;color: white; border: 2px sold rgb(62, 62, 180); margin: 20px;padding:5px;">
            <p style="text-align: center;">
                <img style="max-width: 30px" src="{% static 'img/portal/teacher.png' %}" alt=""><br> 30
            </p>
        </div>
</div>